seed: ${seed}

#train
epochs: 10

loss: 'l2'

optimizer_type: 'adamw'
optimizer:
  lr: 0.001
  weight_decay: 0.00001
  betas: [0.9, 0.999]
  eps: 0.0000001

scheduler:
  T_0: 10
  T_mult: 1
  eta_max: ${trainer.optimizer.lr}
  T_up: 1
  gamma: 1.
  last_epoch: -1


# eval
log_every: 100